name: Deploy Storybook
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Setup .npmrc
        run: |
          echo "@fortawesome:registry=https://npm.fontawesome.com/" > .npmrc
          npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}"

      - name: Install dependencies
        run: |
          npm install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Push Storybook to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git fetch
          git checkout -B gh-pages
          git branch --set-upstream-to=origin/gh-pages gh-pages
          git pull
          git add storybook-static
          git commit -m "Build Storybook (auto-generated commit)"
          git push
